### ISSUE TITLE
Invalid value received

### ISSUE THREAD

**Issue by noisyscott** [metbosch/homebridge-http-temperature#11] opened 2017-10-12 19:10 UTC
I am able to get a bare temperature value out of my Autelis Poolcontrol by visiting an URL, however I cannot seem to get the HttpAccessory to use that data without errors.  Any insight would be very helpful.

Here's my config
`
  "accessory": "HttpTemperature",
  "name": "Pool Temperature",
  "url": "http://192.168.1.201/status/pooltemp",
  "field_name": "",
  "auth": {
    "user": "user",
    "pass": "pass"
    }
}
`
That URL outputs 73 (although there is a trailing space at the end of the output...)

And here's the error
`[Pool Temperature] Error processing received information: Unexpected token 
[Pool Temperature] Error processing received information: Invalid value received`

**Comment by metbosch** [comment] 2017-10-16 06:29
I did some changes to figure what's going wrong. They are in the develop branch of this repo.

Do you know how to temporally use the `develop` branch in your setup? You only have to replace the index.js file of your npm installation by the [index.js](https://github.com/metbosch/homebridge-http-temperature/blob/develop/index.js) of the develop branch. I didn't try the code but I expect it to work.

Please, attach here the new error log.

**Comment by noisyscott** [comment] 2017-10-17 02:37
Thanks!

I installed the develop branch and am now getting the following error:

	Error processing received information: Received value is not a number: “NaN"

**Comment by metbosch** [comment] 2017-10-17 06:56
Hi @noisyscott ,
I think that now it is fixed. Sorry, I didn't test at all the plugin :(
Let me know if you have further problems or if it works now.

**Comment by noisyscott** [comment] 2017-10-17 13:35
Thanks again!

Updated to the latest development branch via the command:

npm install -g https://github.com/metbosch/homebridge-http-temperature.git#develop

Got the following output
"Error processing received information: Received value is not a number: "NaN" ("undefined”)”

Manually opening the URL defined in the config gives me the following output: "50 "

There is definitely a space character at the end of the output.  Maybe I should also reach out to Autelis (the maker of this specific device) and ask them to remove it.

**Comment by metbosch** [comment] 2017-10-17 14:06
Hi,
The space at the end is not the problem.
I will try to create a simple HTTP server that returns "50 " and debug it by myself. Hopefully, I will have some time tomorrow and upload the fix.
Thanks for the info!

**Comment by metbosch** [comment] 2017-10-18 16:25
Hi @noisyscott ,
I'm not able to reproduce the error. My config.json is:
```json
{
    "bridge": {
        "name": "HomebridgePI",
        "username": "CD:22:3D:E3:CE:30",
        "port": 51820,
        "pin": "031-45-156"
    },

    "description": "The Onion!",

    "platforms": [],

    "accessories": [
        {
            "accessory": "HttpTemperature",
            "name": "Outside Temperature",
            "url": "http://192.168.1.146:8000/test",
            "http_method": "GET",
            "field_name": " "
        }
    ]
}
```
And the server is returning what you said: "50 "

I modified the error message to contain the response body which is being parsed. Could you try again and put the new log here?
Also, I realized that your error happens if the `field_name` field in the `config.json` contains a space char or some hidden character. Could you also check it?

**Comment by noisyscott** [comment] 2017-10-18 20:19
Apologies, I had an old config that contained some characters inside the “field_name”.  After ensuring that the field_name was blank made everything work!  Thank you for your great support.

However (totally new issue now) it looks like my thermometer only reports in Fahrenheit, so my pool is reading as 154 degrees right now!  I have been searching around and there’s no current facility for my device it to report in Celsius.  Autelis have been asked to update their firmware to support both Celsius and Fahrenheit, but it’s pretty much falling on deaf ears.

I can kind of fake the correct display of temperature by changing “Settings>General>Language & Region on my phone to use Celsius, but I am not sure what other issues this will cause me down the line.

**Comment by metbosch** [comment] 2017-10-18 21:06
@noisyscott Are you using the develop branch, right? I will merge the small fix into master and publish it to npm.

**Comment by metbosch** [comment] 2017-10-18 21:08
@noisyscott About the units problem,
You mean that you have different units in different accessories endpoints. In addition, ios considers all temperature values with the same units. Consequently, you purpose some mechanism in the plug-in to translate the received value into another units?

**Comment by noisyscott** [comment] 2017-10-18 21:09
Yes, I am using the develop branch.

**Comment by noisyscott** [comment] 2017-10-19 13:19
Not sure I understand the question.

I believe the core issue is that HomeKit expects all values to be Celsius unless informed that this specific device is actually reporting Fahrenheit — otherwise HomeKit via iOS locale settings will dutifully convert the values from Celsius to Fahrenheit. There’s a bit of discussion re: this issue in the main homebridge page

https://github.com/nfarina/homebridge/issues/71 <https://github.com/nfarina/homebridge/issues/71>

**Comment by metbosch** [comment] 2017-12-11 08:14
Closing the issue and following the "celsius <-> fahrenheit" discussion in #15

**Closed by metbosch** 2017-12-11 08:14 UTC
